### ISSUE TITLE
How does the verification of consistency proof works?

### ISSUE THREAD

**Issue by leonardotkimura** [fmerg/pymerkle#15]
How can I know that the firstRoot (or challenge) is present in the proof object? I explain...

The proof of consistency verifies that no information was removed/modified between the two roots. To do so (if I understand well), it (I) uses some nodes to verify/calculate the firstRoot, and (II) uses other nodes to verify/calculate the secondRoot (https://www.rfc-editor.org/rfc/rfc9162#name-example). 

Therefore, given the proof object, you must (1) execute the function proof.verify(); (2) verify the firstRoot; and (3) verify second root. I imagine that the step 3 involves comparing the secondRoot with the proof.commitment. However, I cannot see how to execute the step 2... I can't see how to get the firstRoot from the proof object.

Example. Given the following code:

```
from pymerkle import MerkleTree

tree = MerkleTree()

for data in [b'foo', b'bar', b'baz', b'qux', b'quux']:
    tree.encrypt(data)

state1 = tree.get_root_hash()

for data in [b'corge', b'grault', b'garlpy']:
    tree.encrypt(data)

state2 = tree.get_root_hash()

proof = tree.generate_consistency_proof(challenge=state1)
proof.verify()
```

The consistency proof verifies the consistency between state1 and state2.

The proof object is
```
    ----------------------------------- PROOF ------------------------------------

    uuid        : 66f2bcbd-9e61-11ed-b276-5ccd5b98eb1b

    timestamp   : 1674837669 (Fri Jan 27 13:41:09 2023)
    provider    : 66ee004e-9e61-11ed-b5de-5ccd5b98eb1b

    hash-type   : SHA256
    encoding    : UTF-8
    security    : ACTIVATED


       [0]   +1   2552e3cbf21513bf4b7a8134e4e4a2e1cd8857cc7fe8a51a455ec226e5cf1e6c
       [1]   +1   2e219794e81e9bb22e230e7f40906eecb4cfcc289e1af253d88b23634266c5a2
       [2]   +1   1c0c3f2623f61894bb6ab743c75efe35632b67985777b7017dedcddc3720aae9
       [3]   -1   5b80e74a146a8a28cf4623b7a2463112f2b98633e4c11874e74117f55f8f291c

    offset      : 1

    commitment  : e45204e846a110051b8848afa80d195317c25554358c5d4e2e1363993dd8537b

    -------------------------------- END OF PROOF --------------------------------
```

I imagine that you can compare the state2 with proof.commitment. But I cannot see how to verify state1 using this proof...

Can you help me?

**Comment by fmerg** [comment]
@leonardotkimura you are completely right that state1 cannot be inferred and verified from the proof object. The proof should indicate which of the included hashes are non-leaf nodes and provide a rule for combining them in order to retrieve the initial challenge. This would verify state1. Thank you for pointing this out, i will try to fix as soon as possible.

**Comment by leonardotkimura** [comment]
great! Thank you very much

**Comment by fmerg** [comment]
Handled in version 4.0.0

**Comment by leonardotkimura** [comment]
Thank you very much! We will start building on top of it immediately!

**Comment by fmerg** [comment]
@leonardotkimura note please that the consistency proof does not yet conform to the interface specified in rfc9162. In particular, consistency is not proven among any two arbitrary tree states, but among a previous one and the tree state at the moment of proof generation.

**Comment by fmerg** [comment]
@leonardotkimura New version 5.0.0 conforms to the interface specified in RFC9162 and provides more flexibility with respect to strage
