### ISSUE TITLE
Code Compatibility Issue due to Usage of match/case Statement

### ISSUE THREAD

**Issue by gpericol** [fmerg/pymerkle#22]
Hello,

I've recently encountered an issue with the `resolve` method in the code (proof.py). The problem arises from the usage of the `match`/`case` statement, a feature that was introduced in Python 3.10. This causes syntax errors when the code is run in environments with Python versions lower than 3.10.

Here is the problematic code snippet:

```python
def resolve(self):
    # ...
    match bit:
        case 0:
            result = self.hash_nodes(result, value)
        case 1:
            result = self.hash_nodes(value, result)
        case _:
            raise Exception('Invalid bit found')
    # ...
```

To make the code more compatible across different Python environments, I propose changing the `match`/`case` statement to an `if`/`elif`/`else` statement. Here's what the revised code would look like:

```python
def resolve(self):
    # ...
    if bit == 0:
        result = self.hash_nodes(result, value)
    elif bit == 1:
        result = self.hash_nodes(value, result)
    else:
        raise Exception('Invalid bit found')
    # ...
```

This change would not alter the function's behavior and would greatly improve the code's compatibility.

Let me know if you have any questions or require further information.

**Comment by fmerg** [comment]
Hi @gpericol,

I was actually thinking of dropping support for `python<3.10` you are probably right. I will fix this in the next release. Thank you for noticing this.

**Comment by fmerg** [comment]
Will be handled in #26

**Comment by fmerg** [comment]
Handled in version `6.1.0`
