### ISSUE TITLE
Sakura coding standards

### ISSUE THREAD

**Issue by pyrito** [fmerg/pymerkle#7]
Was just wondering if this implementation made use of the sakura tree hash mode standards to prevent hash collisions (appending extra bits to make sure that there is a differentiation between the intermediate nodes and the root)? Will Kangaroo-Twelve ever be implemented with this as well?

**Comment by FoteinosMerg** [comment]
No, these standards are not currently used. But it would be interesting to start working on such features, including  Kangaroo-Twelve, and any relevant recommendations are welcome. However, priority for the moment would however be to re-implement the project in Cython.
